name: prowlarr
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME}/ContainerDBs/prowlarr:/config
    restart: unless-stopped
    networks:
      - proxy_network
networks:
  proxy_network:
    external: true
