name: valheim

services:
  init-container:
    image: alpine:3.23
    container_name: "valheim-init-container"
    user: root
    command:
      - "/bin/sh"
      - "-c"
      - "chown -R 10001:10001 /srv/valheim/saves && chmod -R g+rwx /srv/valheim/saves && chmod -R g+s /srv/valheim/saves"
    volumes:
      - type: bind
        source: ${HOME}/ContainerDBs/valheim/saves
        target: /srv/valheim/saves
        bind:
          create_host_path: true

  valheim-server:
    image: "pfeiffermax/valheim-dedicated-server:latest"
    pull_policy: always
    container_name: "valheim-server"
    depends_on:
      init-container:
        condition: service_completed_successfully
    command:
      - "-name"
      - "${VALHEIM_SERVER_NAME}"
      - "-world"
      - "${VALHEIM_WORLD_NAME}"
      - "-password"
      - "${VALHEIM_PASSWORD}"
      - "-port"
      - "${VALHEIM_PORT}"
      - "-public"
      - "${VALHEIM_PUBLIC}"
      - "-savedir"
      - "/srv/valheim/saves"
      - "-preset"
      - "normal"
      - "-modifier"
      - "resources"
      - "more"
      - "-modifier"
      - "portals"
      - "casual"
    volumes:
      - type: bind
        source: ${HOME}/ContainerDBs/valheim/saves
        target: /srv/valheim/saves
    networks:
      - proxy_network
    restart: always

networks:
  proxy_network:
    external: true