name: navidrome
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Lisbon
    volumes:
      - ${HOME}/ContainerDBs/navidrome:/data
      - ${HOME}/Media/Music:/music:ro
    restart: unless-stopped
    networks:
      - proxy_network
networks:
  proxy_network:
    external: true
